# Generated by Django 2.2.1 on 2019-05-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_type', models.CharField(max_length=20, verbose_name='水泵型号')),
            ],
        ),
    ]
