# Generated by Django 2.2.1 on 2019-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump_type',
            name='pump_price',
            field=models.IntegerField(default=0),
        ),
    ]
