# Generated by Django 2.2.1 on 2019-05-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='url',
            field=models.URLField(blank='True', default='www.example.com'),
        ),
        migrations.AddField(
            model_name='choice',
            name='voted_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Person', verbose_name='投给谁'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='该投票属于'),
        ),
    ]
